#!/usr/bin/env bash

usage() {
  echo "Usage: compose-dev-env [up|start|stop|down]"
}

if [ $# != 0 ] && [ $1 == "--help" ]; then
  usage
  exit
fi

if [ "$1" == "" ]; then
  usage
  exit
fi

if [[ -f .env ]]; then
  source .env
fi

if [[ -z $USER_NAME ]]; then
  export USER_NAME=$(id -un)
fi 

export USER_ID=$(id -u)
export REGISTRY_ADDRESS=`ip route get 1 | head -1 | sed 's/.*src //g' | cut -d ' ' -f1`

IP=`ip route get 1 | head -1 | sed 's/.*src //g' | cut -d ' ' -f1`

case $1 in
  up)
    docker-compose -p bl -f docker-compose.yaml up -d;;
  start)
    docker-compose -p bl -f docker-compose.yaml start;;
  stop)
    docker-compose -p bl -f docker-compose.yaml stop;;
  down)
    docker-compose -p bl -f docker-compose.yaml down;;
  *)
    usage;;
esac
