#!/usr/bin/env bash

usage() {
  echo "Usage: denv command [options] [suboptions..]"
  echo "where  command can be:"
  echo "           stack - start a development stack"
  echo "                   options are:"
  echo "                       dev - a development stack with 1 kafka broker, 1 zookeeper etc."
  echo "                       hl - dev stack without DISPLAY exposed to run on a headless server"
  echo "                       full - a full stack with 3 kafka brokers, 3 zookeeper etc."
  echo "                   suboptions are:"
  echo "                       up [profile]    - crate and start the stack"
  echo "                       down [profile] - stop and destroy the stack"
  echo "                       start [profile] - start the existing containers in the stack"
  echo "                       stop [profile] - stop the existing containers without destroying the stack"
  echo "                   where profile is the name of the profile you want to use with the stack (default=default)"
  echo "           shell - start an interactive shell in the development environment container"
  echo "                   options are:"
  echo "                       dev <profile> - run an application installed on the dev stack"
  echo "                       hl <profile> - run an application installed on the headless stack"
  echo "                       full <profile> - run an application installed on the full stack"
  echo "                            <profile> is mandatory on all options, use default if you have not created a specific profile"
  echo "                   examples:"
  echo "                       denv shell dev default"
  echo "                       denv shell hl work"
  echo "                       denv shell full myproject"
  echo "           run   - run an application from the development environment container"
  echo "                   options are:"
  echo "                       dev <profile> - run an application installed on the dev stack"
  echo "                       hl <profile> - run an application installed on the headless stack"
  echo "                       full <profile> - run an application installed on the full stack"
  echo "                            <profile> is mandatory on all options, use default if you have not created a specific profile"
  echo "                   suboptions are:"
  echo "                       the application you want to run, e.g. idea.sh, Postman"
  echo "                   examples:"
  echo "                       denv run dev default idea.sh"
  echo "                       denv run dev work Postman"
  echo "                       denv run dev myproject idea.sh"
  echo "           exec  - execute a command from the development environment container"
  echo "                   options are:"
  echo "                       dev <profile> - run an application installed on the dev stack"
  echo "                       hl <profile> - run an application installed on the headless stack"
  echo "                       full <profile> - run an application installed on the full stack"
  echo "                            <profile> is mandatory on all options, use default if you have not created a specific profile"
  echo "                   suboptions are:"
  echo "                        the full command you want to run, e.g. ls -l, ps aux | grep ..."
  echo "                   examples:"
  echo "                       denv exec dev default ls -la"
  echo "                       denv exec dev work ps aux | grep ..."
  echo "                       denv exec dev myproject mkdir -p $HOME/projects/myproject/src"
  echo "           code-server - standalone code-server with no additional services"
  echo "                   options are:"
  echo "                       start [profile] - create a standalone code-server container"
  echo "                       stop  [profile] - stop and destroy the standalone code-server container"
  echo "                   where profile is the development environment profile you want to use (default=default)"
}

if [ $# != 0 ] && [ $1 == "--help" ]; then
  usage
  exit
fi

if [ "$1" == "" ]; then
  usage
  exit
fi

CWD=$(pwd)

if [[ -z $USER_NAME ]]; then
  export USER_NAME=$(id -un)
fi 

export USER_ID=$(id -u)
export REGISTRY_ADDRESS=`ip route get 1 | head -1 | sed 's/.*src //g' | cut -d ' ' -f1`

config_folder=".config/dev-env"
code_server_base_folder=".config/code-server"

if [[ -z $IDEA_VERSION ]]; then 
  IDEA_VERSION="2020.2"
fi

# make sure the docker network exists, and create it if not
# this is to ensure that any containers we create using this script
# connect to the same network and can talk to all the other containers
# that may be deployed
devnet_id=`docker network ls --filter "name=dev-net" -q`

if [[ -z $devnet_id ]]; then 
  echo 'docker network dev-net does not exist, creating...'
  docker network create dev-net
fi

if [[ ! -d ${HOME}/${config_folder}/IntelliJIdea ]] || [[ ! -d ${HOME}/${config_folder}/logs ]]; then
  mkdir -p ${HOME}/${config_folder}/{IntelliJIdea,logs}
fi

#if [[ -f ${HOME}/${config_folder}/.env ]]; then 
#  source ${HOME}/${config_folder}/.env
#fi

command=$1

cd ${HOME}/${config_folder}

case $command in 
  stack)
    shift

    if [[ -z $1 ]] || [[ -z $2 ]]; then
      usage
      exit 1
    fi

    stackprofile=$3

    if [[ -z $3 ]]; then
      echo "Setting stack to default"
      stackprofile=default
    fi

    echo "Stack is now" $stackprofile

    export DEV_ENV_EXTENSIONS_FOLDER=${HOME}/${code_server_base_folder}/${stackprofile}/extensions
    export DEV_ENV_USER_FOLDER=${HOME}/${code_server_base_folder}/${stackprofile}/user-data

    if [[ ! -d ${DEV_ENV_EXTENSIONS_FOLDER} ]]; then
      mkdir -p ${DEV_ENV_EXTENSIONS_FOLDER}
    fi

    if [[ ! -d ${DEV_ENV_USER_FOLDER} ]]; then
      mkdir -p ${DEV_ENV_USER_FOLDER}/{logs,User}
    fi

    case $1 in
      dev)
        case $2 in 
          up)
            docker-compose -p dev_${stackprofile} -f ${HOME}/${config_folder}/docker-compose.yaml up -d;;
          start)
            docker-compose -p dev_${stackprofile} -f ${HOME}/${config_folder}/docker-compose.yaml start;;
          stop)
            docker-compose -p dev_${stackprofile} -f ${HOME}/${config_folder}/docker-compose.yaml stop;;
          down)
            docker-compose -p dev_${stackprofile} -f ${HOME}/${config_folder}/docker-compose.yaml down;;
          *)
            usage;;
        esac
        ;;
      hl)
        case $2 in 
          up)
            docker-compose -p hl_${stackprofile} -f ${HOME}/${config_folder}/docker-compose-headless.yaml up -d;;
          start)
            docker-compose -p hl_${stackprofile} -f ${HOME}/${config_folder}/docker-compose-headless.yaml start;;
          stop)
            docker-compose -p hl_${stackprofile} -f ${HOME}/${config_folder}/docker-compose-headless.yaml stop;;
          down)
            docker-compose -p hl_${stackprofile} -f ${HOME}/${config_folder}/docker-compose-headless.yaml down;;
          *)
            usage;;
        esac
        ;;
      full)
        case $2 in 
          up)
            docker-compose -p full_${stackprofile} -f ${HOME}/${config_folder}/docker-compose-full.yaml up -d;;
          start)
            docker-compose -p full_${stackprofile} -f ${HOME}/${config_folder}/docker-compose-full.yaml start;;
          stop)
            docker-compose -p full_${stackprofile} -f ${HOME}/${config_folder}/docker-compose-full.yaml stop;;
          down)
            docker-compose -p full_${stackprofile} -f ${HOME}/${config_folder}/docker-compose-full.yaml down;;
          *)
            usage;;
        esac
        ;;
    esac
    ;;
  run)
    shift
    xhost +local:$(whoami) 1>${HOME}/${config_folder}/logs/dev-env.log 2>${HOME}/${config_folder}/logs/error.log
    if [[ -z $1 ]] || [[ -z $2 ]]; then
      usage
      exit 1
    fi

    prefix="$1_"

    if [ "$2" != "default" ]; then 
      prefix="$1_$2_"
    fi

    dev_process=`docker ps -f name=${prefix}dev-env -q`

    # If the container is not running, then it doesn't really matter which profile we use to execute the command
    # as the profiles only affect the code server plugins so just use the default
    # otherwise execute the command in the running dev-env

    shift
    shift

    if [[ -z $dev_process ]]; then
      echo 'The dev environment is not running, creating a new container'

      docker run -d --rm \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /run/user/$(id -u):/run/user/$(id -u) \
        -v ${HOME}/code:/home/${USER_NAME}/code \
        -v ${HOME}/.ssh:/home/${USER_NAME}/.ssh \
        -v ${HOME}/.netrc:/home/${USER_NAME}/.netrc \
        -v ${HOME}/.gitconfig:/home/${USER_NAME}/.gitconfig \
        -v ${HOME}/${config_folder}/IntelliJIdea:/home/${USER_NAME}/.IntelliJIdea${IDEA_VERSION} \
        -v ${HOME}/.java:/home/${USER_NAME}/.java \
        -v ${HOME}/.fonts:/home/${USER_NAME}/.fonts \
        -v ${HOME}/${code_server_base_folder}/default/extensions:/code-server/extensions \
        -v ${HOME}/${code_server_base_folder}/default/user-data/User:/code-server/user-data/User \
        -e DISPLAY=$DISPLAY \
        -e DBUS_SESSION_BUS_ADDRESS="unix:path=/var/run/user/1000/bus" \
        -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
        -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
        --ipc=host \
        --security-opt=seccomp:unconfined \
        --network dev-net \
        birchwoodlangham/dockerised-development-environment:latest $@ 1>${HOME}/${config_folder}/logs/dev-env.log 2>${HOME}/${config_folder}/logs/error.log
    else
      docker exec -u $USER_NAME $dev_process $@ & 1>${HOME}/${config_folder}/logs/dev-env.log 2>${HOME}/${config_folder}/logs/error.log
    fi
    ;;
  exec)
    shift

    if [[ -z $1 ]] || [[ -z $2 ]]; then
      usage
      exit 1
    fi

    prefix="$1_"

    if [ "$2" != "default" ]; then 
      prefix="$1_$2_"
    fi

    dev_process=`docker ps -f name=${prefix}dev-env -q`

    if [[ -z $dev_process ]]; then
      echo 'Sorry, the dev environment '${prefix}'dev-env is not running'
      exit 1
    fi

    shift
    shift

    docker exec -u $USER_NAME $dev_process $@
    ;;
  shell)
    shift
    if [[ -z $1 ]] || [[ -z $2 ]]; then
      usage
      exit 1
    fi

    prefix="$1_"

    if [ "$2" != "default" ]; then 
      prefix="$1_$2_"
    fi

    dev_process=`docker ps -f name=${prefix}dev-env -q`

    if [[ -z ${dev_process} ]]; then
      echo 'Development environment '${prefix}'dev-env is not running, starting new environment'

      docker run -it --rm \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR} \
        -v ${HOME}/code:/home/${USER_NAME}/code \
        -v ${HOME}/.ssh:/home/${USER_NAME}/.ssh \
        -v ${HOME}/.netrc:/home/${USER_NAME}/.netrc \
        -v ${HOME}/.gitconfig:/home/${USER_NAME}/.gitconfig \
        -v ${HOME}/${config_folder}/IntelliJIdea:/home/${USER_NAME}/.IntelliJIdea${IDEA_VERSION} \
        -v ${HOME}/.java:/home/${USER_NAME}/.java \
        -v ${HOME}/.fonts:/home/${USER_NAME}/.fonts \
        -v ${HOME}/${code_server_base_folder}/default/extensions:/code-server/extensions \
        -v ${HOME}/${code_server_base_folder}/default/user-data/User:/code-server/user-data/User \
        -e DISPLAY=$DISPLAY \
        -e DBUS_SESSION_BUS_ADDRESS="unix:path=/var/run/user/1000/bus" \
        -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
        -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
        --ipc=host \
        --security-opt=seccomp:unconfined \
        --network dev-net \
        birchwoodlangham/dockerised-development-environment:latest zsh
    else
      echo 'Attaching to current development environment'
      docker exec -it ${dev_process} zsh
    fi

    ;;
  code-server)
    shift

    if [[ -z $1 ]]; then 
      usage
      exit 1
    fi

    profile=default

    if [[ $2 -ne "" ]]; then
      profile=$2
    fi

    case $1 in
      start)
        xhost +local:$(whoami) 1>${HOME}/${config_folder}/logs/dev-env.log 2>${HOME}/${config_folder}/logs/error.log

        docker run -d --rm \
          -v /tmp/.X11-unix:/tmp/.X11-unix \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v /run/user/$(id -u):/run/user/$(id -u) \
          -v ${HOME}/code:/home/${USER_NAME}/code \
          -v ${HOME}/.ssh:/home/${USER_NAME}/.ssh \
          -v ${HOME}/.netrc:/home/${USER_NAME}/.netrc \
          -v ${HOME}/.gitconfig:/home/${USER_NAME}/.gitconfig \
          -v ${HOME}/${config_folder}/IntelliJIdea:/home/${USER_NAME}/.IntelliJIdea2020.1 \
          -v ${HOME}/.java:/home/${USER_NAME}/.java \
          -v ${HOME}/.fonts:/home/${USER_NAME}/.fonts \
          -v ${HOME}/${code_server_base_folder}/${profile}/extensions:/code-server/extensions \
          -v ${HOME}/${code_server_base_folder}/${profile}/user-data/User:/code-server/user-data/User \
          -p 9090:8080 \
          -e DISPLAY=$DISPLAY \
          -e DBUS_SESSION_BUS_ADDRESS="unix:path=/var/run/user/1000/bus" \
          -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
          -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
          --ipc=host \
          --security-opt=seccomp:unconfined \
          --name=dev-env \
          --network dev-net \
          birchwoodlangham/dockerised-development-environment:latest
        ;;
      stop)
        docker stop dev-env
        ;;
      *)
        usage
        ;;  
    esac
    ;;
  *)
    usage
    ;;
esac

cd ${CWD}
