#!/bin/bash

if [[ -f .env ]]; then
  source .env
fi

if [[ -z $USER_NAME ]]; then
  USER_NAME=$(id -u)
fi

docker run -dit --rm -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
  -v $HOME/go:/home/${USER_NAME}/go \
  -v $HOME/code:/home/${USER_NAME}/code \
  -v $HOME/.dev-env-config:/home/${USER_NAME}/.config \
  -v $HOME/.ssh:/home/${USER_NAME}/.ssh \
  -v $HOME/.netrc:/home/${USER_NAME}/.netrc \
  -v $HOME/.gitconfig:/home/${USER_NAME}/.gitconfig \
  -v /run/user/$(id -u):/run/user/$(id -u) \
  -e DBUS_SESSION_BUS_ADDRESS="unix:path=/var/run/user/1000/bus" \
  --ipc=host --name=dev-environment birchwoodlangham/code-dev-environment:latest zsh

