version: "3.7"

volumes:
  postgres-db:

networks:
  dev-net:
    external: true
    name: dev-net

services:
  etcd:
    image: bitnami/etcd:latest
    hostname: etcd
    networks:
      - dev-net
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    restart: on-failure
  # Deprecated by Micro framework in favour of etcd, but we keep it for now
  # until everything has been migrated properly
  consul:
    image: consul
    hostname: consul
    container_name: consul
    networks:
      - dev-net
    restart: on-failure
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - dev-net
    ports:
      - "6379:6379"
    restart: on-failure
  # Micro API service for handling and routing Go-Micro based services
  micro-api:
    image: microhq/micro:latest
    hostname: micro-api
    networks:
      - dev-net
    container_name: micro-api
    env_file:
      - $HOME/.config/dev-env/envfiles/micro.env
    command: ["api"]
    ports:
      - 8080:8080
    restart: on-failure
  # Micro Web service for monitoring Go-Micro based services
  micro-web:
    image: microhq/micro:latest
    hostname: micro-web
    container_name: micro-web
    networks:
      - dev-net
    env_file:
      - $HOME/.config/dev-env/envfiles/micro.env
    ports:
      - 8082:8082
    command: ["web"]
    depends_on:
      - micro-api
    restart: on-failure
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - dev-net
    env_file:
      - $HOME/.config/dev-env/envfiles/zookeeper.env
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
    expose:
      - 2181
    restart: on-failure
  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - dev-net
    depends_on:
      - zookeeper
    env_file:
      - $HOME/.config/dev-env/envfiles/kafka.env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
    restart: on-failure
    ports:
      - 9092:9092
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - dev-net
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
  dev-env:
    image: birchwoodlangham/dockerised-development-environment:latest
    container_name: dev-env
    networks:
      - dev-net
    environment:
      DBUS_SESSION_BUS_ADDRESS: unix:path=/var/run/user/1000/bus
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ipc: host
    ports:
      - 8090:8080
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /run/user/${USER_ID}
        target: /run/user/${USER_ID}
      - type: bind
        source: $HOME/code
        target: /home/${USER_NAME}/code
      - type: bind
        source: $HOME/.ssh
        target: /home/${USER_NAME}/.ssh
      - type: bind
        source: $HOME/.netrc
        target: /home/${USER_NAME}/.netrc
      - type: bind
        source: $HOME/.gitconfig
        target: /home/${USER_NAME}/.gitconfig
      - type: bind
        source: $HOME/.config/dev-env/IntelliJIdea
        target: /home/${USER_NAME}/.IntelliJIdea${IDEA_VERSION}
      - type: bind
        source: $HOME/.java
        target: /home/${USER_NAME}/.java
      - type: bind
        source: $HOME/.fonts
        target: /home/${USER_NAME}/.fonts
      - type: bind
        source: $HOME/code-server/extensions
        target: /code-server/extensions
      - type: bind
        source: $HOME/code-server/user-data/User
        target: /code-server/user-data/User
